title: Klinika Dentare KETIDENT - Shendeti fillon nga goja
description: > # this means to ignore newlines until "baseurl:"
  Klinika dentare me e mire ne Tirane per kirurgjine dentare, trajtimin e mishrave te dhembeve, implateve dhe trajtimeve estetike.
permalink: 'blog/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ketident.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dr. Ketiona Agaj # add your name
author-img: dr.jpg # add your photo
about-author: Shendeti fillon nga goja # add description
social-facebook: klinikadentareketident # add your Facebook handle
social-instagram: ketident # add your Linkedin handle
social-email: info@ketindent.com # add your Email address
social-phone: 00355693919755 # add your Email address
social-whatsapp: 19199138106 # add your Email address

# Tracker
analytics: G-GPWLQC3YWP # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji


paginate: 30
paginate_path: "/page/:num"


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

